### List all

GET http://localhost:3000/laptops

### Get laptop

GET http://localhost:3000/laptops/1

### Create new laptop

POST http://localhost:3000/laptops/
content-type: application/json

{
    "title": "Asus Zephyrus G14 (2023)",
    "price": 3799,
    "brand": "Asus",
    "model": "Zephyrus G14",
    "gpuBrand": "Nvidia",
    "gpuModel": "RTX 4060",
    "vram": "8GB",
    "backlightType": "rgb",
    "processorBrand": "AMD",
    "processorModel": "Ryzen 9 7940HS",
    "cores": 8,
    "threads": 16,
    "ram": "16GB",
    "ramType": "DDR5",
    "storageType": "SSD",
    "storageCapacity": "1TB",
    "screenSize": "14.0",
    "screenResolution": "2560x1600",
    "refreshRate": 165,
    "year": 2023,
    "weight": "1.65kg",
    "description": "Compact yet powerful gaming laptop with excellent build quality and Anime Matrix display",
    "images": ["zephyrus1.jpg", "zephyrus2.jpg"],
    "stockStatus": "in stock"
}
    
### Search for laptops

GET http://localhost:3000/laptops/search?term=Lenovo

### Delete laptop
DELETE http://localhost:3000/laptops/10

### Update laptop
PATCH http://localhost:3000/laptops/308
content-type: application/json

{
    "title": "Asus Zephyrus",
    "price": 20
}

### Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "bigbig111@balls.com",
    "password": "heheasdfasdf"
}

### Change laptop status

PATCH http://localhost:3000/laptops/6
content-type: application/json

{
    "status": "approved"
}