### List all

GET http://localhost:3000/auth

### Get user

GET http://localhost:3000/auth/2

### Create new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "bigbig1@balls.com",
    "password": "heheasdfasdf"
}
    
### Search for laptops

GET http://localhost:3000/auth/search?term=big

### Delete user
DELETE http://localhost:3000/auth/3

### Update user
PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "email": "big@balls1.com",
    "password": "heheasdfasdffff"
}

### Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "bigbig1@balls.com",
    "password": "heheasdfasdf"
}