export type LaptopT = {
  id: number;
  title: string;
  shortDesc: string;
  price: number;
  brand: string;
  model: string;
  graphicsType: 'Integrated' | 'Dedicated';
  gpuBrand?: string;
  gpuModel?: string;
  vram?: string;
  backlightType: string;
  processorBrand: 'Intel' | 'AMD' | 'Apple';
  processorModel: string;
  cores: number;
  threads: number;
  ram: string;
  ramType: 'DDR3' | 'DDR4' | 'DDR5';
  storageType: 'HDD' | 'SSD' | 'HDD + SSD';
  storageCapacity: string;
  screenSize: string;
  screenResolution: string;
  refreshRate: string;
  weight?: string;
  year: number;
  description: string;
  images: string[];
  tag?: string[];
  condition: 'new' | 'like-new' | 'used' | 'damaged';
  stockStatus: 'reserved' | 'sold' | 'in stock';
  status: 'approved' | 'pending' | 'rejected' | 'archived';
  userId: number;
};
